---
- name: "Import common configuration"
  ansible.builtin.import_playbook: ../common/before.yml
- name: "Server configuration"
  hosts: "{{ hosts_group | default('all') }}"
  tasks:
    - name: "Import Wireguard 6to4 tunnel role"
      ansible.builtin.import_role:
        name: "wireguard_4in6_tunnel"
      when:
        - "feature_wireguard_4in6_tunnel | default(false) | bool"
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
    - name: "Create users"
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ 'wheel' if item.sudoernopassword is true }}"
        state: present
      loop: "{{ users }}"
      when: "users is defined and users is iterable"
    - name: "Add SSH authorized keys"
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ item.ssh_authorized_keys }}"
      loop: "{{ users | selectattr('ssh_authorized_keys', 'defined') }}"
      when: "users is defined and users is iterable"
    - name: "Set hostname"
      ansible.builtin.hostname:
        name: "{{ hostname }}"
      when:
        - "hostname is defined"
- name: "Import common configuration"
  ansible.builtin.import_playbook: ../common/after.yml
