---
# ansible/playbooks/configure.yml

- name: "Configure Workstation"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - "../manifest.yml"
  tasks:
    - name: "Import gnome_applications Role"
      ansible.builtin.import_role:
        name: "gnome_applications"
      when:
        - "features.gnome_applications.managed | bool | default (false)"
    - name: "Import gnome_shell Role"
      ansible.builtin.import_role:
        name: "gnome_shell"
      when:
        - "features.gnome_shell.managed | bool | default (false)"
    - name: "Import Oh My Zsh Role"
      ansible.builtin.import_role:
        name: "gantsign.oh-my-zsh"
      when:
        - "features.ohmyzsh.managed | bool | default (false)"